info:
  title: Wordle aided solver
  description: |-
    An app that provides dynamically adjusted optimal suggestions
    for next guesses in the Wordle game.
  url: https://github.com/RLogik
  notes: |-
    The Wordle gamme can for example be found under
    https://www.nytimes.com/games/wordle .
settings:
  # relative to assets folder:
  # path-to-words: words_nyt.txt
  paths:
    - &ref_default_path words_nyt.txt
    - words_full.txt
  path-to-words: *ref_default_path
  # parameters of game:
  size-of-wordle: 5
  max-display-length: 30 # for displaying remaining words in list
  max-length-for-best-optimisation: 1000
  hard-mode: true
  anonymous-feedback: true
