info:
  title: Wordle aided solver.
  description: Internal settings.
settings:
  size-of-wordle: 5
  max-display-length: 10 # for displaying remaining words in list
  max-length-for-best-optimisation: 1000
  hard-mode: true
